language: cpp

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=48
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=48 USE_CMAKE=true
  - os: osx
    compiler: clang
    env:
     - QT_BASE=48
  - os: osx
    compiler: clang
    env:
     - QT_BASE=48 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=51
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=51 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=52
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=52 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=53
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=53 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=54
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=54 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=55
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=55 USE_CMAKE=true
  - os: osx
    compiler: clang
    env:
     - QT_BASE=55
  - os: osx
    compiler: clang
    env:
     - QT_BASE=55 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=56
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=56 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=57
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=57 USE_CMAKE=true
  - os: osx
    compiler: clang
    env:
     - QT_BASE=57
  - os: osx
    compiler: clang
    env:
     - QT_BASE=57 USE_CMAKE=true
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=58
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=58 USE_CMAKE=true
  - os: osx
    compiler: clang
    env:
     - QT_BASE=58
  - os: osx
    compiler: clang
    env:
     - QT_BASE=58 USE_CMAKE=true

before_install:
  - if [[ "$QT_BASE" = "48" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt487-trusty -y; fi
  - if [ "$QT_BASE" = "51" ]; then sudo add-apt-repository ppa:beineri/opt-qt511-trusty -y; fi
  - if [ "$QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521-trusty -y; fi
  - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y; fi
  - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi
  - if [[ "$QT_BASE" = "55" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - if [[ "$QT_BASE" = "58" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [ "$QT_BASE" = "48" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq opt-qt4-qmake opt-qt4-dev-tools; source /opt/qt-4.8/bin/qt-4.8-env.sh;
      else
        brew tap cartr/qt4;
        brew tap-pin cartr/qt4;
        brew install qt;
        brew link --force qt;
      fi
    fi
  - if [ "$QT_BASE" = "51" ]; then sudo apt-get install -qq qt51base; source /opt/qt51/bin/qt51-env.sh; fi
  - if [ "$QT_BASE" = "52" ]; then sudo apt-get install -qq qt52base; source /opt/qt52/bin/qt52-env.sh; fi
  - if [ "$QT_BASE" = "53" ]; then sudo apt-get install -qq qt53base; source /opt/qt53/bin/qt53-env.sh; fi
  - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base; source /opt/qt54/bin/qt54-env.sh; fi
  - if [ "$QT_BASE" = "55" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh;
      else
        brew install qt55;
        brew link --force qt55;
        export QT_NAME="qt@5.5";
        export HOMEBREW_QT5_VERSION=$(brew list --versions $QT_NAME | rev | cut -d' ' -f1 | rev);
        ln -s /usr/local/Cellar/$QT_NAME/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
      fi
    fi
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "57" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh;
      else
        brew install qt@5.7;
        brew link --force qt@5.7;
        export QT_NAME="qt@5.7";
        export HOMEBREW_QT5_VERSION=$(brew list --versions $QT_NAME | rev | cut -d' ' -f1 | rev);
        ln -s /usr/local/Cellar/$QT_NAME/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
      fi
    fi
  - if [ "$QT_BASE" = "58" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh;
      else
        brew install qt5;
        brew link --force qt5;
        export HOMEBREW_QT5_VERSION=$(brew list --versions qt5 | rev | cut -d' ' -f1 | rev);
        ln -s /usr/local/Cellar/qt5/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
      fi
    fi

script:
  - git submodule update --init --recursive

  # build library and binary
  - mkdir ./build && cd ./build
  - if [ "$USE_CMAKE" = "true" ]; then
      cmake --version;
      if [ "$QT_BASE" = "48" ]; then
        cmake -DCMAKE_BUILD_TYPE=Release -DUSE_QT4=ON -DBUILD_TESTS=OFF ..;
      else
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF ..;
      fi

      make;
      ls -lR;
    else
      qmake -v;
      qmake ../qtcsv-example.pro CONFIG+=release LIBS+=-L../qtcsv;
      make;
    fi

  # Execute binary file 
  - cd ./example
  - ./qtcsv-example

notifications:
  email: false
