version: '{build}'

init:
- git config --global core.autocrlf input

environment:
  matrix:
  - QT5: C:\Qt\5.3\mingw482_32
    MINGW: C:\Qt\Tools\mingw482_32
    use_cmake: "false"
  #- QT5: C:\Qt\5.3\mingw482_32
  #  MINGW: C:\Qt\Tools\mingw482_32
  #  use_cmake: "true"
  - QT5: C:\Qt\5.4\mingw491_32
    MINGW: C:\Qt\Tools\mingw491_32
    use_cmake: "false"
  - QT5: C:\Qt\5.5\mingw492_32
    MINGW: C:\Qt\Tools\mingw492_32
    use_cmake: "false"
  - QT5: C:\Qt\5.6\mingw49_32
    MINGW: C:\Qt\Tools\mingw492_32
    use_cmake: "false"
  - QT5: C:\Qt\5.7\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "false"
  - QT5: C:\Qt\5.8\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "false"

matrix:
  fast_finish: true

before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%
- git submodule update --init --recursive

build_script:
- mkdir .\build
- cd .\build

# build library and binary
- if [%use_cmake%]==[true] (
    cmake --version &&
    cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .. &&
    make &&
    dir /s &&
    cd .\example)
  else (
    qmake -v &&
    qmake ..\qtcsv\qtcsv.pro CONFIG+=release DESTDIR=%cd% &&
    mingw32-make &&
    qmake ..\example\example.pro CONFIG+=release DESTDIR=%cd% &&
    mingw32-make &&
    dir /s)

- example.exe
